// ======================================================== SYSTEM INIT
export const FETCH_CRISIS_TYPE_REQUESTED = "FETCH_CRISIS_TYPE_REQUESTED";
export const FETCH_CRISIS_TYPE_SUCCESS = "FETCH_CRISIS_TYPE_SUCCESS";
export const FETCH_CRISIS_TYPE_FAILURE = "FETCH_CRISIS_TYPE_FAILURE";
export const FETCH_ASSISTANCE_TYPE_REQUESTED =
  "FETCH_ASSISTANCE_TYPE_REQUESTED";
export const FETCH_ASSISTANCE_TYPE_SUCCESS = "FETCH_ASSISTANCE_TYPE_SUCCESS";
export const FETCH_ASSISTANCE_TYPE_FAILURE = "FETCH_ASSISTANCE_TYPE_FAILURE";

// ======================================================== COMMON USER
export const FETCH_CRISIS_REQUESTED = "FETCH_CRISIS_REQUESTED";
export const FETCH_CRISIS_SUCCESS = "FETCH_CRISIS_SUCCESS";
export const FETCH_CRISIS_FAILURE = "FETCH_CRISIS_FAILURE";

// ======================================================== MODAL
export const MODAL_SHOW = "MODAL_SHOW";
export const MODAL_HIDE = "MODAL_HIDE";
